name: "Update Changelog"

on:
  release:
    types: [released]

permissions: read-all

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: main

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@a938690fad7edf25368f37e43a1ed1b34303eb36 # v1.12.0
        with:
          latest-version: ${{ github.event.release.name }}
          release-notes: ${{ github.event.release.body }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          branch: chore/update-changelog-${{ github.event.release.tag_name }}
          title: "chore: update CHANGELOG for ${{ github.event.release.tag_name }}"
          body: "Automated changelog update for release ${{ github.event.release.tag_name }}."
          commit-message: "chore: update CHANGELOG for ${{ github.event.release.tag_name }}"
          delete-branch: true
